<?php

namespace App\Service;

/**
 * Stand-in for the customer's own user table.
 *
 * In Modular SSO, Scalekit only asserts "this email authenticated via
 * org X's IdP". The app remains the source of truth for user ids and
 * profile data. This JSON file exists so the demo can show a user
 * record surviving across requests.
 *
 * Swap this class for your real user repository.
 */
class LocalUserStore
{
    public function __construct(private readonly string $storagePath)
    {
    }

    public function findOrCreateByEmail(string $email, string $organizationId, string $connectionId): array
    {
        $users = $this->readAll();

        foreach ($users as $user) {
            if ($user['email'] === $email) {
                return $user;
            }
        }

        $user = [
            // Generated by this app. Not derived from Scalekit `sub`.
            'id' => count($users) + 1,
            'email' => $email,
            'scalekit_organization_id' => $organizationId,
            'scalekit_connection_id' => $connectionId,
        ];

        $users[] = $user;
        $this->writeAll($users);

        return $user;
    }

    public function find(int $id): ?array
    {
        foreach ($this->readAll() as $user) {
            if ($user['id'] === $id) {
                return $user;
            }
        }

        return null;
    }

    private function readAll(): array
    {
        if (!is_file($this->storagePath)) {
            return [];
        }

        return json_decode((string) file_get_contents($this->storagePath), true) ?? [];
    }

    private function writeAll(array $users): void
    {
        $directory = dirname($this->storagePath);
        if (!is_dir($directory)) {
            mkdir($directory, 0777, true);
        }

        file_put_contents($this->storagePath, json_encode($users, JSON_PRETTY_PRINT));
    }
}
